name: Update CP Data

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests cloudscraper curl_cffi

      - name: Test Beecrowd parser
        run: python -m unittest discover -s scripts/tests -p "test_beecrowd.py" -v

      - name: Run updater
        run: python scripts/update_data.py

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Git add
        run: git add data.json

      - name: Git commit
        run: git commit -m "Auto update CP data" || echo "No changes to commit"

      - name: Git push
        run: git push
